### ISSUE TITLE
could not resolve all dependencies for configuration.

### ISSUE THREAD

**Issue by karthi72** [boyw165/my-dlib-experiment#5]
Hi,
 the demo project in [tech-pic-collage ](https://tech.pic-collage.com/face-landmarks-detection-in-your-android-app-part-1-2c4431eaa3d9) series helped me a lot to learn about face detection to get landmarks and dlib integration but when i tried to integrate the sample app it shows me the following error.
> org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':demo-dlib'.
org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':demo-dlib:_debugCompile'.
 
> org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':lib-dlib'.

> Expected NDK STL shared object file at C:\Users\{username}\AppData\Local\Android\Sdk\ndk-bundle\sources\cxx-stl\llvm-libc++\libs\armeabi\libc++_shared.so

**Comment by tcw165** [comment]
Oh, is it the build-tool version is too old in the project. I gotta update it when I'm available.

**Comment by karthi72** [comment]
ok where i need to change those build-tools version?
when i changed the build-tools version.

> ext {
    compileSdkVersion = 27
    buildToolsVersion = '27.0.3'
    minSdkVersion = 21
    targetSdkVersion = 26
    sourceCompatibilityVersion = JavaVersion.VERSION_1_7
    targetCompatibilityVersion = JavaVersion.VERSION_1_7
.....
}


> android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"
.....
}

**Comment by karthi72** [comment]
The main issue is this `Expected NDK STL shared object file at C:\Users\karthi\AppData\Local\Android\Sdk\ndk-bundle\sources\cxx-stl\llvm-libc++\libs\armeabi\libc++_shared.so`.In the above path,not able to see armeabi instead of that armeabi-v7a folder am having.How to change the folder path?

**Comment by tcw165** [comment]
Thanks for your discovery. Now I remember that the latest NDK doesn't support `armeabi` anymore.

<img width="920" alt="screen shot 2018-07-28 at 9 20 25 am" src="https://user-images.githubusercontent.com/6766554/43351638-883c6f1c-9247-11e8-9177-ea526c36726e.png">

So, it'd better to remove the `armeabi` support in the `build.gradle`, for example:

```
        ndk {
            // "x86", "x86_64", "armeabi", "armeabi-v7a", "arm64-v8a"
            abiFilters "x86", "x86_64", "armeabi-v7a", "arm64-v8a"
        }
```

**Comment by tcw165** [comment]
@karthi72 : I just upgrade the Gradle scripts, the project configuration and the dependent libraries. Hope it works for you now.

**Comment by karthi72** [comment]
not able to check the full process it is closing at initializing face detector progress itself.
